const data = {
  products: [
    {
      _id: "1",
      category: "Crno vino",
      image: "/images/vino1.jpg",
      price: 100,
      countInStock: 10,
      sort: "Cabernet Saugvinon",
      rating: 4.5,
      numReviews: 10,
      description: "High quality wine",
    },
    {
      _id: "2",
      category: "Crno vino",
      image: "/images/vino2.jpg",
      price: 110,
      countInStock: 25,
      sort: "Merlot",
      rating: 5,
      numReviews: 12,
      description: "High quality wine",
    },
    {
      _id: "3",
      category: "Crno vino",
      image: "/images/vino3.jpg",
      price: 30,
      countInStock: 15,
      sort: "Lasin",
      rating: 4.5,
      numReviews: 10,
      description: "High quality wine",
    },
    {
      _id: "4",
      category: "Crno vino",
      image: "/images/vino4.jpg",
      price: 90,
      countInStock: 10,
      sort: "Plavina",
      rating: 4.5,
      numReviews: 10,
      description: "High quality wine",
    },
    {
      _id: "5",
      category: "Bijelo vino",
      image: "/images/vino5.jpg",
      price: 49,
      countInStock: 10,
      sort: "Debit",
      rating: 4.5,
      numReviews: 10,
      description: "High quality wine",
    },
  ],
};

export default data;
